package org.jobrunr.examples.embedding.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.annotation.Transient;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

@Table("file_metadata")
public class FileMetadata {

    public enum Status {
        UPDATED,
        DELETED,
    }

    @Id
    private UUID id;
    private final String relativePath;
    private final Instant lastModified;

    @JsonInclude
    @Transient
    private final Status status;

    @PersistenceCreator
    public FileMetadata(UUID id, String relativePath, Instant lastModified) {
        this(id, relativePath, lastModified, Status.UPDATED);
    }

    public FileMetadata(UUID id, String relativePath, Instant lastModified, Status status) {
        this.id = id;
        this.relativePath = relativePath;
        this.lastModified = lastModified;
        this.status = status;
    }

    public UUID getId() {
        return id;
    }

    public String getRelativePath() {
        return relativePath;
    }

    public Instant getLastModified() {
        return lastModified;
    }

    public Status getStatus() {
        return status;
    }

    public static FileMetadata of(String relativePath, Instant lastModified) {
        return new FileMetadata(null, relativePath, lastModified); // id is generated by postgres
    }

    public static FileMetadata updated(FileMetadata fileMetadata) {
        return new FileMetadata(fileMetadata.id, fileMetadata.relativePath, fileMetadata.lastModified);
    }

    public static FileMetadata deleted(FileMetadata fileMetadata) {
        return new FileMetadata(fileMetadata.id, fileMetadata.relativePath, fileMetadata.lastModified, Status.DELETED);
    }
}
